a.out: main.o add_last.o display.o reverse_display.o save.o sync.o delete_last.o
	cc main.o add_last.o display.o reverse_display.o save.o sync.o delete_last.o

main.o:main.c
	cc -c main.c
add_last.o:add_last.c
	cc -c add_last.c
display.o:display.c
	cc -c display.c
reverse_display.o:reverse_display.c
	cc -c reverse_display.c

save.o:save.c
	cc -c save.c

sync.o:sync.c
	cc -c sync.c

delete_last.o:delete_last.c
	cc -c delete_last.c





