a.out:main.o add_last.o display.o save.o sync_file.o
	cc main.o add_last.o display.o save.o sync_file.o

main.o:main.c
	cc -c main.c
add_last.o:add_last.c
	cc -c add_last.c
display.o:display.c
	cc -c display.c
save.o:save.c
	cc -c save.c
sync_file.o:sync_file.c
	cc -c sync_file.c




